### PR TITLE
Added Estate Fishing

### PR DESCRIPTION
**Pull request by The-Synthax**
Added estate fishing support (probably not perfect) with a sanity check to ensure that toon does not wander if the "catch" dialog box fails to appear and the cast button is greyed out.

Edit: Also corrects some other minor issues and should prevent your toon from falling asleep in most cases of failure. Haven't yet come across a situation where it doesn't eventually continue fishing.

### CODE REVIEW

**Comment by VioSynthax** [comment]
Added a note mentioning an error with Doodles.

**Comment by VioSynthax** [comment]
Improves catching errors and prevents Toons from going to bed.

**Comment by witchkilla** [comment]
is this kpreisser? i would like to ask you something. i loved your tt-webinfo for invasions, i loved the robot who spoke. i have all the files on my pc, i was wondering is there a way to connect them with either rewritten or corporate clash to have the same outcome? or can you make a new program that works with either game to let you know of an invasion with a robot voice?

**Comment by kpreisser** [comment]
Hi @The-Synthax,

I'm very sorry that I did not yet review the PR, somehow I always missed it when working on the code (and after 2018 I didn't work on the project for some years). Are you still interested in merging this?
Thanks!

**Comment by The-Synthax** [comment]
> Hi @The-Synthax,
> 
> I'm very sorry that I did not yet review the PR, somehow I always missed it when working on the code (and after 2018 I didn't work on the project for some years). Are you still interested in merging this? Thanks!

Hello! If it's still working (haven't tested since 2018, not sure if Rewritten has had any breaking changes since then) it'd be great to see it merged. Do I need to resubmit the PR?

**Comment by kpreisser** [comment]
Thanks! Yes, please reopen or resubmit the PR. I will then take a look at it when I have some time (probably at the weekend).

**Pull request closed without merging**
